#!/bin/bash
# =============================================================================
# Caddyfile Generator
# =============================================================================
# Reads mocks/*/domains and project.env to produce a complete Caddyfile.
# Output: .generated/Caddyfile
#
# Architecture:
#   - Main app site block → PHP-FPM / app container reverse proxy
#   - One shared site block for all mocked domains → WireMock
#   - Test results static file serving at /test-results/
#   - Optional frontend site block (if FRONTEND_TYPE is set)
#
# Replaces: core/nginx/generate-conf.sh
# =============================================================================

set -euo pipefail

DEVSTACK_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
OUTPUT_DIR="${DEVSTACK_DIR}/.generated"
OUTPUT_FILE="${OUTPUT_DIR}/Caddyfile"

# Source project config
source "${DEVSTACK_DIR}/project.env"

mkdir -p "${OUTPUT_DIR}"

# ---------------------------------------------------------------------------
# Collect all mocked domains
# ---------------------------------------------------------------------------
ALL_MOCK_DOMAINS=()
if [ -d "${DEVSTACK_DIR}/mocks" ]; then
    for mock_dir in "${DEVSTACK_DIR}"/mocks/*/; do
        [ -d "${mock_dir}" ] || continue
        domains_file="${mock_dir}domains"
        [ -f "${domains_file}" ] || continue
        while IFS= read -r domain || [ -n "${domain}" ]; do
            domain=$(echo "${domain}" | tr -d '[:space:]')
            [ -z "${domain}" ] && continue
            [[ "${domain}" == \#* ]] && continue
            ALL_MOCK_DOMAINS+=("${domain}")
        done < "${domains_file}"
    done
fi

echo "[caddy-gen] Found ${#ALL_MOCK_DOMAINS[@]} mocked domains"

# ---------------------------------------------------------------------------
# Global options
# ---------------------------------------------------------------------------
cat > "${OUTPUT_FILE}" <<'CADDY_GLOBAL'
# =============================================================================
# AUTO-GENERATED by devstack — do not edit manually
# Regenerated on every `devstack.sh start`
# =============================================================================
{
    auto_https off
}

CADDY_GLOBAL

# ---------------------------------------------------------------------------
# App server block
# ---------------------------------------------------------------------------
if [ "${APP_TYPE}" = "php-laravel" ]; then
    cat >> "${OUTPUT_FILE}" <<CADDY_APP
# ==========================================================================
# Application server (PHP-FPM)
# ==========================================================================
localhost:80, localhost:443, ${PROJECT_NAME}.local:80, ${PROJECT_NAME}.local:443 {
    tls /certs/server.crt /certs/server.key

    root * /var/www/html/public
    php_fastcgi app:9000
    file_server

    handle_path /test-results/* {
        root * /srv/test-results
        file_server browse
        header Access-Control-Allow-Origin *
        header Cache-Control "no-cache, no-store"
    }
}

CADDY_APP
elif [ -n "${FRONTEND_TYPE:-}" ]; then
    # Frontend + backend: path-based routing
    FRONTEND_API_PREFIX="${FRONTEND_API_PREFIX:-/api}"
    cat >> "${OUTPUT_FILE}" <<CADDY_APP
# ==========================================================================
# Application server (frontend + backend, path-based routing)
# ==========================================================================
localhost:80, localhost:443, ${PROJECT_NAME}.local:80, ${PROJECT_NAME}.local:443 {
    tls /certs/server.crt /certs/server.key

    handle_path ${FRONTEND_API_PREFIX}/* {
        reverse_proxy app:3000
    }

    handle_path /test-results/* {
        root * /srv/test-results
        file_server browse
        header Access-Control-Allow-Origin *
        header Cache-Control "no-cache, no-store"
    }

    handle {
        reverse_proxy frontend:${FRONTEND_PORT:-5173}
    }
}

CADDY_APP
else
    cat >> "${OUTPUT_FILE}" <<CADDY_APP
# ==========================================================================
# Application server (reverse proxy)
# ==========================================================================
localhost:80, localhost:443, ${PROJECT_NAME}.local:80, ${PROJECT_NAME}.local:443 {
    tls /certs/server.crt /certs/server.key

    reverse_proxy app:3000

    handle_path /test-results/* {
        root * /srv/test-results
        file_server browse
        header Access-Control-Allow-Origin *
        header Cache-Control "no-cache, no-store"
    }
}

CADDY_APP
fi

# ---------------------------------------------------------------------------
# Mock proxy — intercepts HTTPS to mocked external services
# All traffic forwarded to WireMock for response generation
# ---------------------------------------------------------------------------
if [ ${#ALL_MOCK_DOMAINS[@]} -gt 0 ]; then
    # Build comma-separated domain list with :443 suffix
    DOMAIN_LIST=""
    DOMAIN_COMMENT=""
    for domain in "${ALL_MOCK_DOMAINS[@]}"; do
        if [ -n "${DOMAIN_LIST}" ]; then
            DOMAIN_LIST="${DOMAIN_LIST}, "
            DOMAIN_COMMENT="${DOMAIN_COMMENT}, "
        fi
        DOMAIN_LIST="${DOMAIN_LIST}${domain}:443"
        DOMAIN_COMMENT="${DOMAIN_COMMENT}${domain}"
    done

    cat >> "${OUTPUT_FILE}" <<CADDY_MOCK
# ==========================================================================
# Mock API Proxy — intercepts HTTPS to mocked external services
# Domains: ${DOMAIN_COMMENT}
# ==========================================================================
${DOMAIN_LIST} {
    tls /certs/server.crt /certs/server.key

    reverse_proxy wiremock:8080 {
        header_up X-Original-Host {http.request.host}
        header_up X-Real-IP {remote_host}
        header_up X-Forwarded-Proto {scheme}
    }
}
CADDY_MOCK
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo "[caddy-gen] Generated ${OUTPUT_FILE}"
echo "[caddy-gen] App: http://localhost:${HTTP_PORT} / https://localhost:${HTTPS_PORT}"
if [ -n "${FRONTEND_TYPE:-}" ]; then
    echo "[caddy-gen] Frontend: proxied via path-based routing (${FRONTEND_API_PREFIX:-/api}/* -> backend)"
fi
if [ ${#ALL_MOCK_DOMAINS[@]} -gt 0 ]; then
    echo "[caddy-gen] Mocked domains (via DNS aliases):"
    for domain in "${ALL_MOCK_DOMAINS[@]}"; do
        echo "  - ${domain}"
    done
fi
