#!/bin/bash
# =============================================================================
# Nginx Configuration Generator
# =============================================================================
# Reads mocks/*/domains and project.env to produce a complete nginx.conf.
# Output: .generated/nginx.conf
#
# Architecture:
#   - Main app server block (HTTP + HTTPS) → PHP-FPM / app container
#   - One proxy server block per mocked domain → WireMock
#   - Test results server block → static file serving
# =============================================================================

set -euo pipefail

DEVSTACK_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
OUTPUT_DIR="${DEVSTACK_DIR}/.generated"
OUTPUT_FILE="${OUTPUT_DIR}/nginx.conf"

# Source project config
source "${DEVSTACK_DIR}/project.env"

mkdir -p "${OUTPUT_DIR}"

# ---------------------------------------------------------------------------
# Collect all mocked domains
# ---------------------------------------------------------------------------
ALL_MOCK_DOMAINS=()
if [ -d "${DEVSTACK_DIR}/mocks" ]; then
    for mock_dir in "${DEVSTACK_DIR}"/mocks/*/; do
        [ -d "${mock_dir}" ] || continue
        domains_file="${mock_dir}domains"
        [ -f "${domains_file}" ] || continue
        while IFS= read -r domain || [ -n "${domain}" ]; do
            domain=$(echo "${domain}" | tr -d '[:space:]')
            [ -z "${domain}" ] && continue
            [[ "${domain}" == \#* ]] && continue
            ALL_MOCK_DOMAINS+=("${domain}")
        done < "${domains_file}"
    done
fi

echo "[nginx-gen] Found ${#ALL_MOCK_DOMAINS[@]} mocked domains"

# ---------------------------------------------------------------------------
# Generate nginx.conf
# ---------------------------------------------------------------------------
cat > "${OUTPUT_FILE}" <<'NGINX_HEAD'
# =============================================================================
# AUTO-GENERATED by devstack — do not edit manually
# Regenerated on every `devstack.sh start`
# =============================================================================

worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;
    sendfile on;
    keepalive_timeout 65;
    client_max_body_size 100M;

    # SSL shared settings
    ssl_certificate     /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

NGINX_HEAD

# ---------------------------------------------------------------------------
# App server block
# ---------------------------------------------------------------------------
if [ "${APP_TYPE}" = "php-laravel" ]; then
    # PHP-FPM: serve static files, proxy .php to FPM
    cat >> "${OUTPUT_FILE}" <<NGINX_APP
    # =========================================================================
    # Application server (PHP-FPM)
    # =========================================================================
    server {
        listen 80;
        listen 443 ssl;
        server_name localhost ${PROJECT_NAME}.local;

        root /var/www/html/public;
        index index.html index.htm index.php;

        location / {
            try_files \$uri \$uri/ /index.php?\$query_string;
        }

        location ~ \\.php\$ {
            fastcgi_pass app:9000;
            fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
            include fastcgi_params;
            fastcgi_read_timeout 300;
            fastcgi_send_timeout 300;
        }

        location /test-results/ {
            alias /var/www/html/public/test-results/;
            autoindex on;
            autoindex_format html;
            add_header Access-Control-Allow-Origin *;
            add_header Cache-Control "no-cache, no-store";
        }
    }

NGINX_APP
else
    # Proxy-based apps (Node, Go, Rust, etc.): reverse proxy to app:3000
    cat >> "${OUTPUT_FILE}" <<NGINX_APP
    # =========================================================================
    # Application server (reverse proxy to app container)
    # =========================================================================
    server {
        listen 80;
        listen 443 ssl;
        server_name localhost ${PROJECT_NAME}.local;

        location / {
            proxy_pass http://app:3000;
            proxy_set_header Host \$host;
            proxy_set_header X-Real-IP \$remote_addr;
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto \$scheme;
            proxy_read_timeout 300;

            # WebSocket support
            proxy_http_version 1.1;
            proxy_set_header Upgrade \$http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        location /test-results/ {
            alias /var/www/html/public/test-results/;
            autoindex on;
            autoindex_format html;
            add_header Access-Control-Allow-Origin *;
            add_header Cache-Control "no-cache, no-store";
        }
    }

NGINX_APP
fi

# ---------------------------------------------------------------------------
# Mock proxy server blocks — one per mocked domain
# ---------------------------------------------------------------------------
if [ ${#ALL_MOCK_DOMAINS[@]} -gt 0 ]; then
    # Build server_name list
    MOCK_SERVER_NAMES=""
    for domain in "${ALL_MOCK_DOMAINS[@]}"; do
        MOCK_SERVER_NAMES="${MOCK_SERVER_NAMES} ${domain}"
    done

    cat >> "${OUTPUT_FILE}" <<NGINX_MOCK
    # =========================================================================
    # Mock API Proxy — intercepts HTTPS to mocked external services
    # All traffic forwarded to WireMock for response generation
    # Mocked domains:${MOCK_SERVER_NAMES}
    # =========================================================================
    server {
        listen 443 ssl;
        server_name${MOCK_SERVER_NAMES};

        location / {
            proxy_pass http://wiremock:8080;
            proxy_set_header Host \$host;
            proxy_set_header X-Real-IP \$remote_addr;
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto \$scheme;
            proxy_set_header X-Original-Host \$host;
            proxy_read_timeout 300;
            proxy_buffering off;
        }
    }

NGINX_MOCK
fi

# ---------------------------------------------------------------------------
# Close http block
# ---------------------------------------------------------------------------
echo "}" >> "${OUTPUT_FILE}"

echo "[nginx-gen] Generated ${OUTPUT_FILE}"
echo "[nginx-gen] App: http://localhost:${HTTP_PORT} / https://localhost:${HTTPS_PORT}"
if [ ${#ALL_MOCK_DOMAINS[@]} -gt 0 ]; then
    echo "[nginx-gen] Mocked domains (via DNS aliases):"
    for domain in "${ALL_MOCK_DOMAINS[@]}"; do
        echo "  - ${domain}"
    done
fi
